bluetooth:
  adapter: hci0 # Linux BT adapter (e.g., hci0)
  discoverable_cmd: "sudo hciconfig {adapter} piscan"
  service_name: "MDP-Group13-RPi" # Human-friendly label
  uuid: "94f39d29-7d6d-437d-973b-fba39e49d4ee" # Your fixed UUID (recommended)
  # If you prefer the standard Serial Port Profile UUID instead of a custom one, set:
  # use_spp_uuid: true
  # spp_uuid: "00001101-0000-1000-8000-00805F9B34FB"
  backlog: 1 # listen() backlog
  recv_bufsize: 1024 # bytes per recv() call
  newline_delimited: true # append '\n' when sending JSON
