api:
  pc_ip: 192.168.13.13
  algo_port: 5000
  image_port: 6000
  # Timeouts (seconds) for outbound HTTP calls from RPi
  timeouts:
    algo: 3   # /path requests to algorithm server
    image: 3  # /stitch and /image requests to image server